security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            
            #form_login:
            #   login_path: app_signin
            #    check_path: app_signin
            #    username_parameter: signin[email]  
            #    password_parameter: signin[password]
            logout:
                path: app_logout
                target: app_login
            #entry_point: form_login  

    # access_control:
    #   - { path: ^/dashboard, roles: ROLE_ADMIN }
    #    - { path: ^/home$, roles: ROLE_USER }  
