security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider  
            logout:
                path: app_logout
                target: app_signin
                
    access_control:
        - { path: ^/user/logout$, roles: ROLE_USER }
        - { path: ^/user/Profile$, roles: ROLE_USER }
        - { path: ^/user/edit$, roles: ROLE_USER }
        - { path: ^/user/canelacc$, roles: ROLE_USER }
        - { path: ^/user/changepass$, roles: ROLE_USER }



        - { path: ^/dashboard$, roles: ROLE_ADMIN }
